# Generated by Django 4.1.2 on 2022-11-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(default='Thu Nov 03 2022', max_length=50),
        ),
    ]
